import type { ServiceResolverEntry } from './serviceResolver.js';

/** Starter es-CL seed. It is not the complete Chile taxonomy. */
export const CHILE_LOCAL_SERVICE_SEED: readonly ServiceResolverEntry[] = [
  {
    serviceId: 'home.plumbing.general',
    discoveryGroupKey: 'HOME_REPAIR_MAINTENANCE',
    label: 'Gasfitería',
    aliases: ['gasfiter', 'gasfiteria', 'plomero', 'cañerías', 'tuberías', 'fugas de agua'],
    intentPhrases: ['tengo una fuga', 'se rompió una cañería', 'necesito un gasfiter'],
    archetypeCandidates: ['FIELD_SERVICE', 'PROJECT_QUOTE'],
  },
  {
    serviceId: 'home.plumbing.drain_unclogging',
    discoveryGroupKey: 'HOME_REPAIR_MAINTENANCE',
    label: 'Destape y alcantarillado',
    aliases: ['destape', 'alcantarillado', 'wc tapado', 'baño tapado', 'cañería tapada', 'desagüe tapado'],
    intentPhrases: ['se tapó el wc', 'se tapó el lavaplatos', 'no corre el desagüe'],
    archetypeCandidates: ['FIELD_SERVICE'],
  },
  {
    serviceId: 'home.electrical.general',
    discoveryGroupKey: 'HOME_REPAIR_MAINTENANCE',
    label: 'Electricidad',
    aliases: ['electricista', 'instalación eléctrica', 'reparación eléctrica', 'enchufe', 'tablero eléctrico'],
    intentPhrases: ['se cortó la luz en la casa', 'necesito un electricista'],
    archetypeCandidates: ['FIELD_SERVICE', 'PROJECT_QUOTE'],
  },
  {
    serviceId: 'home.locksmith.general',
    discoveryGroupKey: 'HOME_REPAIR_MAINTENANCE',
    label: 'Cerrajería',
    aliases: ['cerrajero', 'cerradura', 'llaves', 'chapa', 'apertura de puerta'],
    intentPhrases: ['quedé fuera de la casa', 'perdí las llaves'],
    archetypeCandidates: ['FIELD_SERVICE'],
  },
  {
    serviceId: 'home.hot_water.calefont',
    discoveryGroupKey: 'HOME_REPAIR_MAINTENANCE',
    label: 'Reparación y mantención de calefont',
    aliases: ['calefont', 'calefón', 'mantención calefont', 'reparación calefont'],
    archetypeCandidates: ['FIELD_SERVICE', 'PROJECT_QUOTE'],
  },
  {
    serviceId: 'home.hvac.air_conditioning',
    discoveryGroupKey: 'HOME_REPAIR_MAINTENANCE',
    label: 'Aire acondicionado y climatización para hogar',
    aliases: ['aire acondicionado', 'climatización', 'calefacción', 'hvac'],
    negativeTerms: ['automotriz', 'auto', 'vehículo'],
    archetypeCandidates: ['FIELD_SERVICE', 'PROJECT_QUOTE'],
  },
  {
    serviceId: 'home.gardening.general',
    discoveryGroupKey: 'HOME_REPAIR_MAINTENANCE',
    label: 'Jardinería y mantención de jardines',
    aliases: ['jardinero', 'jardinería', 'mantención jardín', 'paisajismo', 'riego'],
    intentPhrases: ['necesito cortar el pasto', 'mantener el jardín'],
    archetypeCandidates: ['FIELD_SERVICE'],
  },
  {
    serviceId: 'home.cleaning.general',
    discoveryGroupKey: 'CLEANING_LAUNDRY_HOME_CARE',
    label: 'Limpieza y aseo',
    aliases: ['aseo', 'limpieza hogar', 'limpieza profunda', 'limpieza de casa'],
    archetypeCandidates: ['FIELD_SERVICE'],
  },
  {
    serviceId: 'moving.local_freight',
    discoveryGroupKey: 'MOVING_LOGISTICS_DELIVERY',
    label: 'Mudanza y flete',
    aliases: ['mudanza', 'flete', 'mini flete', 'transporte de carga', 'retiro y entrega'],
    archetypeCandidates: ['DISPATCH_LOGISTICS', 'PROJECT_QUOTE'],
  },
  {
    serviceId: 'auto.tires.vulcanization',
    discoveryGroupKey: 'AUTO_MOTO_MOBILITY',
    label: 'Neumáticos y vulcanización',
    aliases: ['neumáticos', 'neumaticos', 'vulcanización', 'vulcanizacion', 'alineación', 'balanceo'],
    archetypeCandidates: ['RETAIL', 'PROJECT_QUOTE'],
  },
  {
    serviceId: 'auto.window_film',
    discoveryGroupKey: 'AUTO_MOTO_MOBILITY',
    label: 'Polarizado y láminas para vehículos',
    aliases: ['polarizado', 'lámina automotriz', 'film automotriz', 'polarizado auto'],
    negativeTerms: ['casa', 'oficina', 'edificio', 'ventana hogar'],
    archetypeCandidates: ['PROJECT_QUOTE'],
  },
  {
    serviceId: 'building.window_film',
    discoveryGroupKey: 'CONSTRUCTION_INSTALLATION',
    label: 'Láminas para vidrios de casas y oficinas',
    aliases: ['polarizado', 'lámina de seguridad', 'lámina control solar', 'film arquitectónico', 'film de vidrio'],
    negativeTerms: ['auto', 'automotriz', 'vehículo'],
    archetypeCandidates: ['PROJECT_QUOTE', 'FIELD_SERVICE', 'WHOLESALE_B2B'],
  },
  {
    serviceId: 'tech.computer_repair',
    discoveryGroupKey: 'TECH_ELECTRONICS_COMMUNICATION',
    label: 'Reparación de computadores y notebooks',
    aliases: ['computador', 'computadores', 'notebook', 'notebooks', 'macbook', 'servicio técnico computador'],
    intentPhrases: ['mi notebook no prende', 'computador lento'],
    archetypeCandidates: ['PROJECT_QUOTE', 'FIELD_SERVICE'],
  },
  {
    serviceId: 'beauty.hair_salon',
    discoveryGroupKey: 'BEAUTY_PERSONAL_CARE',
    label: 'Peluquería',
    aliases: ['peluquería', 'peluqueria', 'corte de pelo', 'coloración', 'tintura', 'alisado'],
    archetypeCandidates: ['APPOINTMENT_SERVICE', 'RETAIL'],
  },
  {
    serviceId: 'pets.grooming',
    discoveryGroupKey: 'PETS',
    label: 'Peluquería canina',
    aliases: ['peluquería canina', 'peluqueria canina', 'baño perro', 'grooming mascotas'],
    archetypeCandidates: ['APPOINTMENT_SERVICE', 'FIELD_SERVICE'],
  },
  {
    serviceId: 'education.languages',
    discoveryGroupKey: 'EDUCATION_CLASSES',
    label: 'Clases de idiomas',
    aliases: ['idiomas', 'inglés', 'ingles', 'español para extranjeros', 'clases de inglés'],
    archetypeCandidates: ['SCHEDULED_CAPACITY', 'APPOINTMENT_SERVICE'],
  },
  {
    serviceId: 'print.apparel_customization',
    discoveryGroupKey: 'TECH_ELECTRONICS_COMMUNICATION',
    label: 'Estampado y personalización de ropa',
    aliases: ['estampado', 'estampados', 'poleras personalizadas', 'impresión de poleras', 'sublimación textil'],
    negativeTerms: ['reparación impresora', 'impresora dañada'],
    archetypeCandidates: ['MAKE_TO_ORDER', 'PROJECT_QUOTE'],
  },
];
