import { DEFAULT_LOCALE, type PaltaLocale } from './locales.js';

export const ES_CL_UI = {
  'nav.home': 'Inicio',
  'nav.neighborhood': 'Barrio',
  'nav.community': 'Comunidad',
  'nav.market': 'Mercado',
  'nav.play': 'Panorama',
  'nav.businesses': 'Negocios',
  'common.language': 'Idioma',
  'common.settings': 'Configuración',
  'common.back': 'Volver',
  'common.retry': 'Intentar de nuevo',
  'common.processing': 'Procesando…',
  'common.view': 'Ver',
  'common.verified': 'Verificado',
  'auth.checkingSession': 'Comprobando tu sesión…',
  'auth.signInOrSignUp': 'Inicia sesión o crea una cuenta',
  'auth.continueApple': 'Continuar con Apple',
  'auth.continueGoogle': 'Continuar con Google',
  'auth.email': 'Correo electrónico',
  'auth.sendEmailLink': 'Enviar enlace por correo',
  'auth.emailLinkSent': 'Enviamos un enlace de acceso a',
  'auth.openSameDevice': 'Abre el enlace en este dispositivo para volver a Palta.',
  'auth.signOut': 'Cerrar sesión',
  'settings.language': 'Idioma',
  'settings.languageDescription': 'Elige el idioma de Palta. Si una traducción no existe, verás el original en español.',
  'home.subtitle': 'Tu vida, más cerca',
  'home.loading': 'Actualizando tu día…',
  'home.emptyTitle': 'Nada urgente por ahora',
  'home.emptyBody': 'Palta no necesita llenar la pantalla si no hay nada útil que mostrar.',
  'home.sectionTitle': 'Para ti, ahora',
  'home.sectionSubtitle': 'Primero lo que requiere atención; después lo que realmente ayuda hoy.',
  'home.eyebrowNow': 'AHORA',
  'home.eyebrowInProgress': 'EN CURSO',
  'home.eyebrowForToday': 'PARA HOY',
  'home.eyebrowToday': 'HOY',
  'home.careTracking': 'Ver seguimiento',
  'home.showMore': 'Ver {count} más',
  'home.quietEnd': 'Eso es todo lo útil por ahora.',
  'neighborhood.title': 'Tu barrio',
  'neighborhood.permissionSubtitle': 'La ubicación se usa sólo cuando hace falta',
  'neighborhood.nearbyPrompt': '¿Qué hay cerca de ti?',
  'neighborhood.locationUseExplanation': 'Palta usa tu ubicación mientras estás usando esta pantalla. No la convierte automáticamente en tu casa o zona de vida.',
  'neighborhood.locating': 'Buscando ubicación…',
  'neighborhood.useLocation': 'Usar mi ubicación',
  'neighborhood.useDevelopmentLocation': 'Usar ubicación de desarrollo',
  'neighborhood.activeSubtitle': 'Ubicación activa · editable',
  'neighborhood.mapPrepared': 'Map Core preparado',
  'neighborhood.mapStyleMissing': 'Falta conectar EXPO_PUBLIC_MAP_STYLE_URL.',
  'neighborhood.searchArea': 'Buscar en esta zona',
  'neighborhood.openNow': 'Abierto ahora',
  'neighborhood.nearYou': 'CERCA DE TI',
  'neighborhood.loading': 'Buscando cerca…',
  'neighborhood.emptyTitle': 'No encontramos resultados aquí',
  'neighborhood.emptyBody': 'Puedes mover el mapa o cambiar la búsqueda.',
  'neighborhood.locationRestricted': 'Activa la ubicación para Palta desde Ajustes.',
  'neighborhood.locationDenied': 'Sin permiso de ubicación puedes explorar otra zona manualmente.',
  'neighborhood.locationUnavailable': 'No pudimos obtener tu ubicación.',
  'community.title': 'Comunidad',
  'community.subtitle': 'Personas y grupos, con límites claros',
  'community.myGroupsTitle': 'Mis grupos',
  'community.myGroupsSubtitle': 'Escuela, iglesia, organización o grupos privados que ya forman parte de tu vida.',
  'community.neighborhoodTitle': 'Tu barrio',
  'community.neighborhoodSubtitle': 'Conversaciones y avisos locales con un alcance claro.',
  'community.discoverTitle': 'Descubrir',
  'community.discoverSubtitle': 'Contenido público local sin revelar tus membresías privadas.',
  'business.genericTitle': 'Negocio',
  'business.loading': 'Cargando negocio…',
  'business.noData': 'No hay datos disponibles.',
  'business.verificationNote': 'Verificación: {status}. Los datos públicos pueden verse; cupones y ofertas controladas requieren propietario verificado.',
  'business.actionTitle': '¿Qué quieres hacer?',
  'business.actionSubtitle': 'Palta muestra sólo acciones que este negocio puede ofrecer.',
  'business.sendingQuote': 'Enviando solicitud…',
  'business.quoteQueued': 'Guardamos tu solicitud. Palta volverá a enviarla cuando recupere conexión.',
  'business.sendFailed': 'No se pudo enviar la solicitud.',
  'business.adapterPending': 'La acción “{capability}” ya está definida, pero su conexión todavía no está disponible.',
  'business.canonicalId': 'ID canónico: {id}',
  'business.action.call': 'Llamar',
  'business.action.whatsapp': 'WhatsApp',
  'business.action.save': 'Guardar',
  'business.action.quote': 'Cotizar',
  'business.action.reservation': 'Reservar',
  'business.action.queue': 'Tomar turno',
  'business.action.inquiry': 'Consultar',
  'business.action.coupon': 'Cupón',
  'business.action.pricing': 'Precios',
} as const;

export type UiKey = keyof typeof ES_CL_UI;
export type UiInterpolation = Record<string, string | number>;
type UiCatalog = Partial<Record<UiKey, string>>;

const KO_UI: UiCatalog = {
  'nav.home': '홈',
  'nav.neighborhood': '동네',
  'nav.community': '커뮤니티',
  'nav.market': '마켓',
  'nav.play': '놀자',
  'nav.businesses': '동네업체',
  'common.language': '언어',
  'common.settings': '설정',
  'common.back': '뒤로',
  'common.retry': '다시 시도',
  'common.processing': '처리 중…',
  'common.view': '보기',
  'common.verified': '인증됨',
  'auth.checkingSession': '로그인 상태를 확인하고 있습니다.',
  'auth.signInOrSignUp': '로그인 또는 회원가입',
  'auth.continueApple': 'Apple로 계속',
  'auth.continueGoogle': 'Google로 계속',
  'auth.email': '이메일',
  'auth.sendEmailLink': '이메일 링크 보내기',
  'auth.emailLinkSent': '로그인 링크를 보냈습니다:',
  'auth.openSameDevice': '같은 기기에서 링크를 열면 Palta로 돌아옵니다.',
  'auth.signOut': '로그아웃',
  'settings.language': '언어',
  'settings.languageDescription': 'Palta에서 사용할 언어를 선택하세요. 번역이 없는 내용은 스페인어 원문으로 표시됩니다.',
  'home.subtitle': '내 생활을 더 가까이',
  'home.loading': '오늘 필요한 정보를 업데이트하고 있습니다…',
  'home.emptyTitle': '지금 급한 일은 없습니다',
  'home.emptyBody': '도움이 되는 내용이 없으면 Palta는 화면을 억지로 채우지 않습니다.',
  'home.sectionTitle': '지금 나에게 필요한 것',
  'home.sectionSubtitle': '먼저 확인이 필요한 일, 그다음 오늘 실제로 도움이 되는 내용을 보여줍니다.',
  'home.eyebrowNow': '지금',
  'home.eyebrowInProgress': '진행 중',
  'home.eyebrowForToday': '오늘 할 일',
  'home.eyebrowToday': '오늘',
  'home.careTracking': '진행 상황 보기',
  'home.showMore': '{count}개 더 보기',
  'home.quietEnd': '지금은 여기까지 확인하면 됩니다.',
  'neighborhood.title': '내 동네',
  'neighborhood.permissionSubtitle': '위치는 필요할 때만 사용합니다',
  'neighborhood.nearbyPrompt': '내 주변에는 무엇이 있을까요?',
  'neighborhood.locationUseExplanation': 'Palta는 이 화면을 사용하는 동안에만 현재 위치를 사용합니다. 현재 위치를 자동으로 집이나 생활권으로 저장하지 않습니다.',
  'neighborhood.locating': '위치를 찾고 있습니다…',
  'neighborhood.useLocation': '현재 위치 사용',
  'neighborhood.useDevelopmentLocation': '개발용 위치 사용',
  'neighborhood.activeSubtitle': '현재 위치 사용 중 · 변경 가능',
  'neighborhood.mapPrepared': 'Map Core 준비됨',
  'neighborhood.mapStyleMissing': 'EXPO_PUBLIC_MAP_STYLE_URL 연결이 필요합니다.',
  'neighborhood.searchArea': '이 지역에서 다시 검색',
  'neighborhood.openNow': '지금 영업 중',
  'neighborhood.nearYou': '내 주변',
  'neighborhood.loading': '주변을 찾고 있습니다…',
  'neighborhood.emptyTitle': '이 지역에서 결과를 찾지 못했습니다',
  'neighborhood.emptyBody': '지도를 움직이거나 검색 조건을 바꿔보세요.',
  'neighborhood.locationRestricted': '설정에서 Palta의 위치 사용을 허용해 주세요.',
  'neighborhood.locationDenied': '위치 권한 없이도 다른 지역을 직접 탐색할 수 있습니다.',
  'neighborhood.locationUnavailable': '현재 위치를 가져오지 못했습니다.',
  'community.title': '커뮤니티',
  'community.subtitle': '관계의 범위를 분명하게 나눕니다',
  'community.myGroupsTitle': '내 그룹',
  'community.myGroupsSubtitle': '학교, 교회, 단체처럼 이미 내 생활에 연결된 비공개 그룹입니다.',
  'community.neighborhoodTitle': '내 동네',
  'community.neighborhoodSubtitle': '범위가 분명한 지역 대화와 공지를 확인합니다.',
  'community.discoverTitle': '둘러보기',
  'community.discoverSubtitle': '내 비공개 소속을 노출하지 않고 지역 공개 콘텐츠를 확인합니다.',
  'business.genericTitle': '업체',
  'business.loading': '업체 정보를 불러오고 있습니다…',
  'business.noData': '표시할 업체 정보가 없습니다.',
  'business.verificationNote': '인증 상태: {status}. 공개 정보는 볼 수 있지만 쿠폰과 관리형 혜택은 인증된 업주만 제공할 수 있습니다.',
  'business.actionTitle': '무엇을 하시겠습니까?',
  'business.actionSubtitle': '이 업체가 실제로 제공할 수 있는 기능만 보여줍니다.',
  'business.sendingQuote': '요청을 보내고 있습니다…',
  'business.quoteQueued': '요청을 저장했습니다. 인터넷 연결이 복구되면 Palta가 다시 전송합니다.',
  'business.sendFailed': '요청을 보내지 못했습니다.',
  'business.adapterPending': '“{capability}” 기능의 계약은 준비되어 있지만 실제 연결은 아직 사용할 수 없습니다.',
  'business.canonicalId': 'Canonical ID: {id}',
  'business.action.call': '전화',
  'business.action.whatsapp': 'WhatsApp',
  'business.action.save': '저장',
  'business.action.quote': '견적 요청',
  'business.action.reservation': '예약',
  'business.action.queue': '대기 등록',
  'business.action.inquiry': '문의',
  'business.action.coupon': '쿠폰',
  'business.action.pricing': '가격',
};

const EN_UI: UiCatalog = {
  'nav.home': 'Home',
  'nav.neighborhood': 'Neighborhood',
  'nav.community': 'Community',
  'nav.market': 'Market',
  'nav.play': 'Things to do',
  'nav.businesses': 'Businesses',
  'common.language': 'Language',
  'common.settings': 'Settings',
  'common.back': 'Back',
  'common.retry': 'Try again',
  'common.processing': 'Processing…',
  'common.view': 'View',
  'common.verified': 'Verified',
  'auth.checkingSession': 'Checking your sign-in status…',
  'auth.signInOrSignUp': 'Sign in or create an account',
  'auth.continueApple': 'Continue with Apple',
  'auth.continueGoogle': 'Continue with Google',
  'auth.email': 'Email',
  'auth.sendEmailLink': 'Send email link',
  'auth.emailLinkSent': 'We sent a sign-in link to',
  'auth.openSameDevice': 'Open the link on this device to return to Palta.',
  'auth.signOut': 'Sign out',
  'settings.language': 'Language',
  'settings.languageDescription': 'Choose the language Palta uses. If a translation is unavailable, the Spanish original is shown.',
  'home.subtitle': 'Your life, closer',
  'home.loading': 'Updating your day…',
  'home.emptyTitle': 'Nothing urgent right now',
  'home.emptyBody': 'Palta does not need to fill the screen when there is nothing useful to show.',
  'home.sectionTitle': 'For you, now',
  'home.sectionSubtitle': 'What needs attention first, followed by what genuinely helps today.',
  'home.eyebrowNow': 'NOW',
  'home.eyebrowInProgress': 'IN PROGRESS',
  'home.eyebrowForToday': 'FOR TODAY',
  'home.eyebrowToday': 'TODAY',
  'home.careTracking': 'View progress',
  'home.showMore': 'View {count} more',
  'home.quietEnd': 'That is everything useful for now.',
  'neighborhood.title': 'Your neighborhood',
  'neighborhood.permissionSubtitle': 'Location is used only when needed',
  'neighborhood.nearbyPrompt': 'What is near you?',
  'neighborhood.locationUseExplanation': 'Palta uses your location while you are using this screen. It does not automatically turn your current location into your home or living area.',
  'neighborhood.locating': 'Finding your location…',
  'neighborhood.useLocation': 'Use my location',
  'neighborhood.useDevelopmentLocation': 'Use development location',
  'neighborhood.activeSubtitle': 'Location active · editable',
  'neighborhood.mapPrepared': 'Map Core ready',
  'neighborhood.mapStyleMissing': 'EXPO_PUBLIC_MAP_STYLE_URL still needs to be connected.',
  'neighborhood.searchArea': 'Search this area',
  'neighborhood.openNow': 'Open now',
  'neighborhood.nearYou': 'NEAR YOU',
  'neighborhood.loading': 'Searching nearby…',
  'neighborhood.emptyTitle': 'No results found here',
  'neighborhood.emptyBody': 'Move the map or change your search.',
  'neighborhood.locationRestricted': 'Enable location for Palta in Settings.',
  'neighborhood.locationDenied': 'You can still explore another area manually without location permission.',
  'neighborhood.locationUnavailable': 'We could not get your location.',
  'community.title': 'Community',
  'community.subtitle': 'People and groups, with clear boundaries',
  'community.myGroupsTitle': 'My groups',
  'community.myGroupsSubtitle': 'School, church, organizations, or private groups already connected to your life.',
  'community.neighborhoodTitle': 'Your neighborhood',
  'community.neighborhoodSubtitle': 'Local conversations and notices with a clear scope.',
  'community.discoverTitle': 'Discover',
  'community.discoverSubtitle': 'Public local content without exposing your private memberships.',
  'business.genericTitle': 'Business',
  'business.loading': 'Loading business…',
  'business.noData': 'No business data is available.',
  'business.verificationNote': 'Verification: {status}. Public data can be viewed; controlled coupons and offers require a verified owner.',
  'business.actionTitle': 'What would you like to do?',
  'business.actionSubtitle': 'Palta only shows actions this business can actually offer.',
  'business.sendingQuote': 'Sending request…',
  'business.quoteQueued': 'We saved your request. Palta will send it again when the connection is restored.',
  'business.sendFailed': 'The request could not be sent.',
  'business.adapterPending': 'The “{capability}” action is defined, but its live connection is not available yet.',
  'business.canonicalId': 'Canonical ID: {id}',
  'business.action.call': 'Call',
  'business.action.whatsapp': 'WhatsApp',
  'business.action.save': 'Save',
  'business.action.quote': 'Request quote',
  'business.action.reservation': 'Reserve',
  'business.action.queue': 'Join queue',
  'business.action.inquiry': 'Ask',
  'business.action.coupon': 'Coupon',
  'business.action.pricing': 'Prices',
};

const ZH_HANS_UI: UiCatalog = {
  'nav.home': '首页',
  'nav.neighborhood': '附近',
  'nav.community': '社区',
  'nav.market': '市场',
  'nav.play': '活动',
  'nav.businesses': '商家',
  'common.language': '语言',
  'common.settings': '设置',
  'common.back': '返回',
  'common.retry': '重试',
  'common.processing': '处理中…',
  'common.view': '查看',
  'common.verified': '已认证',
  'auth.checkingSession': '正在检查登录状态…',
  'auth.signInOrSignUp': '登录或注册',
  'auth.continueApple': '使用 Apple 继续',
  'auth.continueGoogle': '使用 Google 继续',
  'auth.email': '电子邮箱',
  'auth.sendEmailLink': '发送邮箱登录链接',
  'auth.emailLinkSent': '登录链接已发送至',
  'auth.openSameDevice': '请在此设备上打开链接以返回 Palta。',
  'auth.signOut': '退出登录',
  'settings.language': '语言',
  'settings.languageDescription': '选择 Palta 的显示语言。没有翻译时，将显示西班牙语原文。',
  'home.subtitle': '让生活离你更近',
  'home.loading': '正在更新今天的信息…',
  'home.emptyTitle': '目前没有紧急事项',
  'home.emptyBody': '没有真正有用的内容时，Palta 不会为了填满屏幕而添加信息。',
  'home.sectionTitle': '现在与你相关',
  'home.sectionSubtitle': '先显示需要处理的事项，再显示今天真正有帮助的内容。',
  'home.eyebrowNow': '现在',
  'home.eyebrowInProgress': '进行中',
  'home.eyebrowForToday': '今日事项',
  'home.eyebrowToday': '今天',
  'home.careTracking': '查看进度',
  'home.showMore': '再查看 {count} 项',
  'home.quietEnd': '目前有用的信息就这些。',
  'neighborhood.title': '你的附近',
  'neighborhood.permissionSubtitle': '仅在需要时使用位置',
  'neighborhood.nearbyPrompt': '你附近有什么？',
  'neighborhood.locationUseExplanation': 'Palta 只会在你使用此页面时使用当前位置，不会自动把当前位置保存为你的住址或生活区域。',
  'neighborhood.locating': '正在获取位置…',
  'neighborhood.useLocation': '使用我的位置',
  'neighborhood.useDevelopmentLocation': '使用开发位置',
  'neighborhood.activeSubtitle': '位置已启用 · 可更改',
  'neighborhood.mapPrepared': 'Map Core 已准备',
  'neighborhood.mapStyleMissing': '仍需连接 EXPO_PUBLIC_MAP_STYLE_URL。',
  'neighborhood.searchArea': '搜索此区域',
  'neighborhood.openNow': '现在营业',
  'neighborhood.nearYou': '你附近',
  'neighborhood.loading': '正在搜索附近…',
  'neighborhood.emptyTitle': '此区域没有找到结果',
  'neighborhood.emptyBody': '可以移动地图或更改搜索条件。',
  'neighborhood.locationRestricted': '请在设置中允许 Palta 使用位置。',
  'neighborhood.locationDenied': '即使不授予位置权限，也可以手动浏览其他区域。',
  'neighborhood.locationUnavailable': '无法获取你的当前位置。',
  'community.title': '社区',
  'community.subtitle': '人与群组，并保持清晰边界',
  'community.myGroupsTitle': '我的群组',
  'community.myGroupsSubtitle': '学校、教会、组织或已经与你生活相关的私人群组。',
  'community.neighborhoodTitle': '你的附近',
  'community.neighborhoodSubtitle': '查看范围明确的本地交流和通知。',
  'community.discoverTitle': '发现',
  'community.discoverSubtitle': '在不公开私人群组关系的情况下浏览本地公开内容。',
  'business.genericTitle': '商家',
  'business.loading': '正在加载商家信息…',
  'business.noData': '暂无可显示的商家信息。',
  'business.verificationNote': '认证状态：{status}。公开信息可以查看；受控优惠券和优惠需要经过认证的商家所有者。',
  'business.actionTitle': '你想做什么？',
  'business.actionSubtitle': 'Palta 只显示该商家实际可以提供的操作。',
  'business.sendingQuote': '正在发送请求…',
  'business.quoteQueued': '请求已保存。恢复网络连接后，Palta 会再次发送。',
  'business.sendFailed': '无法发送请求。',
  'business.adapterPending': '“{capability}”操作已定义，但实时连接尚不可用。',
  'business.canonicalId': 'Canonical ID：{id}',
  'business.action.call': '电话',
  'business.action.whatsapp': 'WhatsApp',
  'business.action.save': '保存',
  'business.action.quote': '询价',
  'business.action.reservation': '预约',
  'business.action.queue': '加入排队',
  'business.action.inquiry': '咨询',
  'business.action.coupon': '优惠券',
  'business.action.pricing': '价格',
};

const CATALOGS: Record<PaltaLocale, UiCatalog> = {
  'es-CL': ES_CL_UI,
  ko: KO_UI,
  en: EN_UI,
  'zh-Hans': ZH_HANS_UI,
};

export interface UiTranslationResult {
  text: string;
  locale: PaltaLocale;
  usedFallback: boolean;
}

function interpolate(template: string, values?: UiInterpolation): string {
  if (!values) return template;
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key: string) => {
    const value = values[key];
    return value === undefined ? match : String(value);
  });
}

export function resolveUiText(key: UiKey, locale: PaltaLocale): UiTranslationResult {
  const translated = CATALOGS[locale][key];
  if (translated?.trim()) return { text: translated, locale, usedFallback: false };
  return { text: ES_CL_UI[key], locale: DEFAULT_LOCALE, usedFallback: locale !== DEFAULT_LOCALE };
}

export function t(
  key: UiKey,
  locale: PaltaLocale,
  values?: UiInterpolation,
): string {
  return interpolate(resolveUiText(key, locale).text, values);
}
