import type { PlayDiscoveryItem } from '../../../../src/play/playDiscovery';

/**
 * Development-only visual fixtures.
 *
 * Production never publishes these records. They are already normalized to the
 * Play projection contract so the runtime preview does not depend on a particular
 * ingestion/source adapter being present in the composition branch.
 */
export const playPreviewItems: readonly PlayDiscoveryItem[] = [
  {
    id: 'preview-municipal-vitacura-family',
    canonicalKey: 'preview:event:vitacura-family',
    sourceKind: 'municipal_event',
    contentKind: 'workshop',
    eventId: 'preview-event-vitacura-family',
    venueId: 'preview-venue-vitacura-cultural',
    title: 'Taller familiar en centro cultural',
    comuna: 'Vitacura',
    venue: 'Centro cultural',
    scheduleLabel: 'Hoy · 16:00',
    startAt: '2026-09-18T16:00:00-03:00',
    isFree: true,
    registrationRequired: true,
    audienceLabel: 'Familias',
    themeTags: ['today', 'family', 'free'],
    imageUrl: 'https://picsum.photos/seed/palta-family-workshop/900/600',
    distanceLabel: 'Cerca de ti',
    experienceTags: ['Familia', 'Taller', 'Gratis'],
    source: { authority: 'Municipalidad · ejemplo' },
  },
  {
    id: 'preview-municipal-las-condes-outdoor',
    canonicalKey: 'preview:event:las-condes-outdoor',
    sourceKind: 'municipal_event',
    contentKind: 'family_activity',
    eventId: 'preview-event-las-condes-outdoor',
    venueId: 'preview-venue-las-condes-park',
    title: 'Actividad al aire libre para niños',
    comuna: 'Las Condes',
    venue: 'Parque comunal',
    scheduleLabel: 'Hoy · 17:30',
    startAt: '2026-09-18T17:30:00-03:00',
    isFree: true,
    audienceLabel: 'Niños y familias',
    themeTags: ['today', 'family', 'free', 'outdoor'],
    imageUrl: 'https://picsum.photos/seed/palta-outdoor-kids/900/600',
    distanceLabel: '18 min',
    travelTimeMinutes: 18,
    experienceTags: ['Niños', 'Parque', 'Gratis'],
    source: { authority: 'Municipalidad · ejemplo' },
  },
  {
    id: 'preview-public-providencia-music',
    canonicalKey: 'preview:event:providencia-music',
    sourceKind: 'public_program',
    contentKind: 'concert',
    eventId: 'preview-event-providencia-music',
    title: 'Música y cultura en el barrio',
    comuna: 'Providencia',
    venue: 'Espacio público',
    scheduleLabel: 'Hoy · 19:00',
    startAt: '2026-09-18T19:00:00-03:00',
    isFree: true,
    audienceLabel: 'Todo público',
    themeTags: ['today', 'free', 'outdoor'],
    imageUrl: 'https://picsum.photos/seed/palta-music-public/900/600',
    distanceLabel: '22 min',
    travelTimeMinutes: 22,
    experienceTags: ['Música', 'Cultura', 'Gratis'],
    source: { authority: 'Agenda pública · ejemplo' },
  },
  {
    id: 'preview-catalog-movie',
    canonicalKey: 'preview:event:movie-1810',
    sourceKind: 'partner_feed',
    contentKind: 'movie',
    eventId: 'preview-event-movie-1810',
    title: 'Película en cartelera cerca de ti',
    comuna: 'Las Condes',
    venue: 'Cine · ejemplo',
    scheduleLabel: 'Hoy · funciones desde 18:10',
    startAt: '2026-09-18T18:10:00-03:00',
    priceLabel: 'Entradas disponibles',
    distanceLabel: '14 min',
    travelTimeMinutes: 14,
    experienceTags: ['Cine', 'Cartelera'],
    imageUrl: 'https://picsum.photos/seed/palta-cinema-showtime/900/600',
    themeTags: ['today'],
    source: { authority: 'Cartelera · ejemplo' },
  },
  {
    id: 'preview-catalog-performance',
    canonicalKey: 'preview:event:performance-weekend',
    sourceKind: 'partner_feed',
    contentKind: 'live_performance',
    eventId: 'preview-event-performance-weekend',
    title: 'Espectáculo familiar este fin de semana',
    comuna: 'Providencia',
    venue: 'Sala · ejemplo',
    scheduleLabel: 'Este finde · 17:00',
    startAt: '2026-09-19T17:00:00-03:00',
    priceLabel: 'Ver entradas',
    distanceLabel: '21 min',
    travelTimeMinutes: 21,
    audienceLabel: 'Familiar',
    experienceTags: ['Espectáculo', 'Familia'],
    imageUrl: 'https://picsum.photos/seed/palta-live-performance/900/600',
    themeTags: ['weekend', 'family'],
    source: { authority: 'Cartelera · ejemplo' },
  },
  {
    id: 'preview-business-birthday-pool',
    canonicalKey: 'preview:offering:birthday-pool',
    sourceKind: 'business',
    contentKind: 'birthday',
    offeringId: 'preview-offering-birthday-pool',
    businessId: 'preview-business-birthday-pool',
    businessProjection: {
      businessId: 'preview-business-birthday-pool',
      offeringId: 'preview-offering-birthday-pool',
      exposureReason: 'birthday_pool',
      ownerManaged: false,
    },
    title: 'Cumpleaños con piscina',
    comuna: 'Chicureo',
    scheduleLabel: 'Reserva previa',
    audienceLabel: '5–12 años · 15–30 personas',
    priceLabel: 'Desde $300.000',
    distanceLabel: '32 min',
    travelTimeMinutes: 32,
    experienceTags: ['Piscina', 'Aire libre', 'Cumpleaños'],
    imageUrl: 'https://picsum.photos/seed/palta-birthday-pool/900/600',
    themeTags: ['birthday', 'family', 'outdoor'],
    source: { authority: 'Negocio · ejemplo' },
  },
] as const;
